services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  web_api:
    image: lems2503/nurbnb-alojamiento
    container_name: web_api_application
    ports:
      - "5000:80"

  web_api_usuario:
    image: klbraguilar/nurbnb-usuario
    container_name: web_api_usuario
    ports:
      - "8001:80"  

networks:
  default:
    driver: bridge