services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password

  web_api:
    image: lems2503/nurbnb-alojamiento
    container_name: web_api_application
    ports:
      - "8001:80"
    depends_on:
      - sql

networks:
  default:
    driver: bridge
